steps:
#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: silent-service-321315
    _ZONE: us-central1-a
    _GKE_CLUSTER: vivek
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: sampleapp
    _CONTAINERNAME: sampleapp
    _REPO_NAME: cicd-service
    
    # Developers ONLY change
    _VERSION: v2.0
    
options:
    substitution_option: 'ALLOW_LOOSE'

